[build]
  publish = "frontend"
  command = "echo 'Frontend only - no build needed'"
  
[build.environment]
  NODE_VERSION = "18"
  # Disable Python/pip auto-installation
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
  # Skip Python detection
  PYTHON_VERSION = ""

# Ignore Python files during build detection
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "https://place-search-gen-ai.onrender.com/:splat"
  status = 200
  force = false