services:
  # Backend API Service
  - type: web
    name: placediscover-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SERPSTACK_API_KEY
        sync: false
    healthCheckPath: /
